In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
Path = 'drive/My Drive/DATASETS'

In [5]:
import pandas as pd
df = pd.read_csv (Path+'/apple_data.csv')
df.head()

,Date,Year,Month,Day,DayOfWeek,Open,High,Low,Close,Volume,Adj Close
0,2020-01-02,2020,1,2,3,74.059998,75.150002,73.797501,75.087502,135480400,73.059425
1,2020-01-03,2020,1,3,4,74.287498,75.144997,74.125000,74.357498,146322800,72.349121
2,2020-01-06,2020,1,6,0,73.447502,74.989998,73.187500,74.949997,118387200,72.925629
3,2020-01-07,2020,1,7,1,74.959999,75.224998,74.370003,74.597504,108872000,72.582649
4,2020-01-08,2020,1,8,2,74.290001,76.110001,74.290001,75.797501,132079200,73.750237

In [6]:
print("First 5 rows of the dataset:")
print (df.head())

First 5 rows of the dataset:
         Date  Year  Month  Day  DayOfWeek       Open       High        Low  \
0  2020-01-02  2020      1    2          3  74.059998  75.150002  73.797501
1  2020-01-03  2020      1    3          4  74.287498  75.144997  74.125000
2  2020-01-06  2020      1    6          0  73.447502  74.989998  73.187500
3  2020-01-07  2020      1    7          1  74.959999  75.224998  74.370003
4  2020-01-08  2020      1    8          2  74.290001  76.110001  74.290001

       Close     Volume  Adj Close
0  75.087502  135480400  73.059425
1  74.357498  146322800  72.349121
2  74.949997  118387200  72.925629
3  74.597504  108872000  72.582649
4  75.797501  132079200  73.750237

In [7]:
print("/nBasic information about the dataset:")
print(df.info())

/nBasic information about the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       996 non-null    object
 1   Year       996 non-null    int64
 2   Month      996 non-null    int64
 3   Day        996 non-null    int64
 4   DayOfWeek  996 non-null    int64
 5   Open       996 non-null    float64
 6   High       996 non-null    float64
 7   Low        996 non-null    float64
 8   Close      996 non-null    float64
 9   Volume     996 non-null    int64
 10  Adj Close  996 non-null    float64
dtypes: float64(5), int64(5), object(1)
memory usage: 85.7+ KB
None

In [8]:
print("/nSummary statistics for numerical columns:")
print(df.describe())

/nSummary statistics for numerical columns:
              Year       Month         Day   DayOfWeek        Open  \
count   996.000000  996.000000  996.000000  996.000000  996.000000
mean   2021.493976    6.560241   15.729920    2.030120  140.708519
std       1.118579    3.429313    8.761746    1.394568   33.345145
min    2020.000000    1.000000    1.000000    0.000000   57.020000
25%    2020.000000    4.000000    8.000000    1.000000  123.625002
50%    2021.000000    7.000000   16.000000    2.000000  145.540001
75%    2022.000000   10.000000   23.000000    3.000000  166.495007
max    2023.000000   12.000000   31.000000    4.000000  198.020004

             High         Low       Close        Volume   Adj Close
count  996.000000  996.000000  996.000000  9.960000e+02  996.000000
mean   142.351436  139.174239  140.835956  9.894002e+07  139.241185
std     33.461959   33.214426   33.344698  5.452482e+07   33.693434
min     57.125000   53.152500   56.092499  2.404830e+07   54.707001
25%    124.965002  122.064999  123.502501  6.405055e+07  121.404333
50%    147.264999  144.120003  145.860001  8.448145e+07  144.116127
75%    168.597500  165.057495  166.277496  1.156058e+08  164.790398
max    199.619995  197.000000  198.110001  4.265100e+08  197.857529

In [9]:
print("/nMissing values in the dataset:")
print(df.isnull())

/nMissing values in the dataset:
      Date   Year  Month    Day  DayOfWeek   Open   High    Low  Close  \
0    False  False  False  False      False  False  False  False  False
1    False  False  False  False      False  False  False  False  False
2    False  False  False  False      False  False  False  False  False
3    False  False  False  False      False  False  False  False  False
4    False  False  False  False      False  False  False  False  False
..     ...    ...    ...    ...        ...    ...    ...    ...    ...
991  False  False  False  False      False  False  False  False  False
992  False  False  False  False      False  False  False  False  False
993  False  False  False  False      False  False  False  False  False
994  False  False  False  False      False  False  False  False  False
995  False  False  False  False      False  False  False  False  False

     Volume  Adj Close
0     False      False
1     False      False
2     False      False
3     False      False
4     False      False
..      ...        ...
991   False      False
992   False      False
993   False      False
994   False      False
995   False      False

[996 rows x 11 columns]